# Generated by Django 3.1.4 on 2021-01-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='complete',
            field=models.BooleanField(verbose_name=True),
        ),
    ]
