# Generated by Django 3.1.4 on 2021-01-13 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210113_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='todolist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todolist', to='polls.todolist'),
        ),
    ]
